---
sudo: false
language: ruby
dist: trusty
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.6.0"
  - PUPPET_GEM_VERSION="~> 4.7.0"
  - PUPPET_GEM_VERSION="~> 4.8.0"
  - PUPPET_GEM_VERSION="~> 4.9.0"
matrix:
  exclude:
  - rvm: 2.1.10
    env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.9.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.9.0"
